vpc = "phils-vpc"
private_subnet = "phils-private-subnet"
public_subnet = "phils-public-subnet"
key_name = "bastion_key"
public_key = "<PUBLIC_KEY>"
private_sg_name = "private_sg"
public_sg_name = "public_sg"
gw_name = "phils_gw"
